name: Deploy to Staging

on:
  push:
    branches:
      - feature/staging-environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for Node compatibility

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3  # Updated to v3 for Node compatibility
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: npm run build

      - name: Sync files to S3
        run: |
          aws s3 sync ./build s3://token-staging

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E27M4DYHWJTNNC --paths "/*"